sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t CosminBadea1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true CosminBadea1/docker-react npm run test
